name: Docker CD

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:

  docker:
    name: Deploy Seeder Image
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/bittorrent-seeder
          restrict-to: kiwix/seeder
          platforms: |
            linux/amd64
            linux/arm64
          registries: ghcr.io
          manual-tag: develop
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
